import mongoose from "mongoose";

const productCategorySchema = new mongoose.Schema({
  Laptops: [
    {
      product_id: { type: String, required: true },
      imageURL: { type: String, required: true, trim: true },
      detailUrl: String,
      quantity: Number,
      Name: { type: String, required: true },
      title: { type: String },
      ratings: String,
      price: String,
      tagline: String,
      description: String,
      cuttedPrice: String,
      discount: Number,
    },
  ],
  Bags: [
    {
      product_id: { type: String, required: true },
      imageURL: { type: String, required: true, trim: true },
      detailUrl: String,
      quantity: Number,
      Name: { type: String, required: true },
      title: { type: String },
      ratings: String,
      price: String,
      tagline: String,
      description: String,
      cuttedPrice: String,
      discount: String,
    },
  ],
  ComputerTables: [
    {
      product_id: { type: String, required: true },
      imageURL: { type: String, required: true, trim: true },
      detailUrl: String,
      quantity: Number,
      Name: { type: String, required: true },
      title: { type: String },
      ratings: String,
      price: String,
      tagline: String,
      description: String,
      cuttedPrice: String,
      discount: String,
    },
  ],
  Wifi: [
    {
      product_id: { type: String, required: true },
      imageURL: { type: String, required: true, trim: true },
      detailUrl: String,
      quantity: Number,
      Name: { type: String, required: true },
      title: { type: String },
      ratings: String,
      price: String,
      tagline: String,
      description: String,
      cuttedPrice: String,
      discount: String,
    },
  ],
  Chairs: [
    {
      product_id: { type: String, required: true },
      imageURL: { type: String, required: true, trim: true },
      detailUrl: String,
      quantity: Number,
      Name: { type: String, required: true },
      title: { type: String },
      ratings: String,
      price: String,
      tagline: String,
      description: String,
      cuttedPrice: String,
      discount: String,
    },
  ],
  shoes: [
    {
      product_id: { type: String, required: true },
      imageURL: { type: String, required: true, trim: true },
      detailUrl: String,
      quantity: Number,
      Name: { type: String, required: true },
      title: { type: String },
      ratings: String,
      price: String,
      tagline: String,
      description: String,
      cuttedPrice: String,
      discount: String,
    },
  ],
  Mobile_Accessories: [
    {
      product_id: { type: String, required: true },
      imageURL: { type: String, required: true, trim: true },
      detailUrl: String,
      quantity: Number,
      Name: { type: String, required: true },
      title: { type: String },
      ratings: String,
      price: String,
      tagline: String,
      description: String,
      cuttedPrice: String,
      discount: String,
    },
  ],
});

const allProductsModel = mongoose.model("Productlist", productCategorySchema);
export default allProductsModel;
